client:
  connectTimeout: 10000
  ms-college:
    url: http://localhost:8093/colleges
  readTimeout: 10000
logging:
  level:
    org:
      springframework:
        web: DEBUG
server:
  port: 8095
spring:
  datasource:
    #TODO I will use liquibase from next week.
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Er159951.
    url: jdbc:mysql://db4free.net:3306/student_task
    username: nigarmovsumova
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
